include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for DDNS Web
LUCI_DEPENDS:=+luci-base +ddns-web
LUCI_PKGARCH:=all
PKG_VERSION:=1.6.11
PKG_RELEASE:=2
PKG_MAINTAINER:=lgyong511

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
